sudo: false

language: node_js
node_js:
  - "4"
  - "6"
  - "7"
  - "8"

cache:
  directories:
    $HOME/.npm

before_install:
  # prevent the npm loading indicator
  - npm config --global set spin false
  # if npm version is less 3.0.0 (lets say 1.x or 2.x) we should attempt to upgrade to 3
  - if [[ $(npm -v | cut -d '.' -f 1) -lt 3 ]]; then npm i -g npm@^3; fi

install:
  - travis_retry npm install

script:
  - npm run test

deploy:
  provider: npm
  email: stefan.penner+ember-cli@gmail.com
  api_key:
    secure: P8rw+xVuDSHQOH1dB4Rf5aTh5uqZFZ6Ioht3MmYfxlnVjW0xG6F4gQWsd8P7baSV++Fybm5WYPjCsWGA3pB3EZFD05zTT/7BQ8AIsPYU7rBmNbbtaTibCcj0qhJJtxRhmbDTzzvRfcE2ETyOuT42ZVczTvOPBxCtyb8kJyentCg=
  on:
    tags: true
    repo: ember-cli/blprnt
